version: '3.6'

services: 
  web: 
    build: .
    command: python ./api/manage.py runserver 0.0.0.0:8000
    ports: 
      - '8000:8000'
  # web:
  #   build: .
  #   command: jupyter notebook --allow-root --port=8888 --ip=0.0.0.0
  #   ports: 
  #      - '8888:8888'